### ISSUE TITLE
Instructions for how to use shims along with nvm commands

### ISSUE THREAD

**Issue by jonocodes** [iamogbz/nvshim#149]
**Is your feature request related to a problem? Please describe.**

To get this plugin my .zshrc looks like this

```
# source /usr/share/nvm/init-nvm.sh
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
export NVSHIM_VERBOSE=true
```

The shim works well as I switch directories. However if I want to manage my node versions, I no longer have access to the npm command, since was instructed to comment out the init as above.

**Describe the solution you'd like**

Ideally there would be a way to use the shim and the npm management commands in the same terminal session.

**Describe alternatives you've considered**

For now I can work around this in my current shell by manually running:
`source /usr/share/nvm/init-nvm.sh`

Then I can run npm list, install, etc. However that session will no longer work with the shim.

**Comment by iamogbz** [comment]
@jonocodes I'm assuming you mean `nvm` commands? Since `npm` commands are shimmed and still accessible. Might be able to fix this by providing a shim specifically for running `nvm` commands. Will look into this, thanks! Also feel free to open up PR with fix suggestions if you have any

**Comment by iamogbz** [comment]
@jonocodes should be able to run `nvm` commands using the shim in the released version. Some commands that modify the current shell will have no effect e.g. `nvm use` etc. though that should be expected. Feel free to reopen if it does not work as expected.

**Comment by jonocodes** [comment]
Just tried it, and it works as expected!
Thanks so much for this fix/responsiveness and your contribution to great open source tools.
:bow:
