### ISSUE TITLE
Killing a node process prints a KeyboardInterrupt stack trace from the shim

### ISSUE THREAD

**Issue by noahnu** [iamogbz/nvshim#68]
**Describe the bug**

Killing a node process prints a KeyboardInterrupt stack trace. It's noisy.

**To Reproduce**

Run webpack dev server via nvshim. Use Ctrl+C to kill the process. See stack trace.

**Expected behavior**

No stack trace. nvshim should be "invisible" to the user.

**Screenshots**

![image](https://user-images.githubusercontent.com/1297096/76420401-6e8a3c80-6378-11ea-8242-df45a77b3cc1.png)

**Desktop (please complete the following information):**
- OS: Mac OS Catalina 10.15.3
- nvshim 1.0.4

**Comment by iamogbz** [comment]
Open to PRs 🙏
